class CustomError(Exception):
    a=int(input('hjghguk5'))
    pass
try:
    a=int(input("enter the number"))
except CustomError:
    print("fgh")    